export const ASSETS_TABS_SET = 'ASSETS_TABS_SET';

export const TRANSPARENT_TOKENS_DEPOSIT_DIALOG_SHOW = 'TRANSPARENT_TOKENS_DEPOSIT_DIALOG_SHOW';
export const TRANSPARENT_TOKENS_DEPOSIT_DIALOG_HIDE = 'TRANSPARENT_TOKENS_DEPOSIT_DIALOG_HIDE';

export const TRANSPARENT_TOKENS_WITHDRAW_DIALOG_SHOW = 'TRANSPARENT_TOKENS_WITHDRAW_DIALOG_SHOW';
export const TRANSPARENT_TOKENS_WITHDRAW_DIALOG_HIDE = 'TRANSPARENT_TOKENS_WITHDRAW_DIALOG_HIDE';
