export const ASSETS_TABS_SET = 'ASSETS_TABS_SET';

export const TRANSPARENT_TOKENS_DEPOSIT_DIALOG_SHOW = 'TRANSPARENT_TOKENS_DEPOSIT_DIALOG_SHOW';
export const TRANSPARENT_TOKENS_DEPOSIT_DIALOG_HIDE = 'TRANSPARENT_TOKENS_DEPOSIT_DIALOG_HIDE';

export const TRANSPARENT_TOKENS_WITHDRAW_DIALOG_SHOW = 'TRANSPARENT_TOKENS_WITHDRAW_DIALOG_SHOW';
export const TRANSPARENT_TOKENS_WITHDRAW_DIALOG_HIDE = 'TRANSPARENT_TOKENS_WITHDRAW_DIALOG_HIDE';

export const TRANSPARENT_TOKENS_TRANSFER_DIALOG_SHOW = 'TRANSPARENT_TOKENS_TRANSFER_DIALOG_SHOW';
export const TRANSPARENT_TOKENS_TRANSFER_DIALOG_HIDE = 'TRANSPARENT_TOKENS_TRANSFER_DIALOG_HIDE';

export const TRANSPARENT_TOKENS_CONVERT_DIALOG_SHOW = 'TRANSPARENT_TOKENS_CONVERT_DIALOG_SHOW';
export const TRANSPARENT_TOKENS_CONVERT_DIALOG_HIDE = 'TRANSPARENT_TOKENS_CONVERT_DIALOG_HIDE';

export const SHIELDED_TOKENS_DEPOSIT_DIALOG_SHOW = 'SHIELDED_TOKENS_DEPOSIT_DIALOG_SHOW';
export const SHIELDED_TOKENS_DEPOSIT_DIALOG_HIDE = 'SHIELDED_TOKENS_DEPOSIT_DIALOG_HIDE';

export const SHIELDED_TOKENS_WITHDRAW_DIALOG_SHOW = 'SHIELDED_TOKENS_WITHDRAW_DIALOG_SHOW';
export const SHIELDED_TOKENS_WITHDRAW_DIALOG_HIDE = 'SHIELDED_TOKENS_WITHDRAW_DIALOG_HIDE';

export const SHIELDED_TOKENS_TRANSFER_DIALOG_SHOW = 'SHIELDED_TOKENS_TRANSFER_DIALOG_SHOW';
export const SHIELDED_TOKENS_TRANSFER_DIALOG_HIDE = 'SHIELDED_TOKENS_TRANSFER_DIALOG_HIDE';

export const SHIELDED_TOKENS_CONVERT_DIALOG_SHOW = 'SHIELDED_TOKENS_CONVERT_DIALOG_SHOW';
export const SHIELDED_TOKENS_CONVERT_DIALOG_HIDE = 'SHIELDED_TOKENS_CONVERT_DIALOG_HIDE';

