export const GAS_PRICE_FETCH_IN_PROGRESS = 'GAS_PRICE_FETCH_IN_PROGRESS';
export const GAS_PRICE_FETCH_SUCCESS = 'GAS_PRICE_FETCH_SUCCESS';
export const GAS_PRICE_FETCH_ERROR = 'GAS_PRICE_FETCH_ERROR';

export const GAS_ESTIMATION_FETCH_IN_PROGRESS = 'GAS_ESTIMATION_FETCH_IN_PROGRESS';
export const GAS_ESTIMATION_FETCH_SUCCESS = 'GAS_ESTIMATION_FETCH_SUCCESS';
export const GAS_ESTIMATION_FETCH_ERROR = 'GAS_ESTIMATION_FETCH_ERROR';
