export const IBC_TRANSFER_AMOUNT_SET = 'IBC_TRANSFER_AMOUNT_SET';
export const IBC_TRANSFER_TYPE_SET = 'IBC_TRANSFER_TYPE_SET';
export const IBC_SWAP_TYPE_SET = 'IBC_SWAP_TYPE_SET';
export const IBC_TRANSFER_ADDRESS_SET = 'IBC_TRANSFER_ADDRESS_SET';
export const SELECT_CHAIN_SET = 'SELECT_CHAIN_SET';
export const SELECT_ASSET_SET = 'SELECT_ASSET_SET';
export const FROM_NAMADA_SELECT_ASSET_SET = 'FROM_NAMADA_SELECT_ASSET_SET';
export const FROM_SHIELDED_NAMADA_SELECT_ASSET_SET = 'FROM_SHIELDED_NAMADA_SELECT_ASSET_SET';
export const IBC_TRANSFER_IN_PROGRESS = 'IBC_TRANSFER_IN_PROGRESS';
export const IBC_TRANSFER_SUCCESS = 'IBC_TRANSFER_SUCCESS';
export const IBC_TRANSFER_ERROR = 'IBC_TRANSFER_ERROR';

export const CONNECT_IBC_ACCOUNT_IN_PROGRESS = 'CONNECT_IBC_ACCOUNT_IN_PROGRESS';
export const CONNECT_IBC_ACCOUNT_SUCCESS = 'CONNECT_IBC_ACCOUNT_SUCCESS';
export const CONNECT_IBC_ACCOUNT_ERROR = 'CONNECT_IBC_ACCOUNT_ERROR';
export const KEPLR_ACCOUNT_KEYS_SET = 'KEPLR_ACCOUNT_KEYS_SET';

export const TIMEOUT_HEIGHT_FETCH_IN_PROGRESS = 'TIMEOUT_HEIGHT_FETCH_IN_PROGRESS';
export const TIMEOUT_HEIGHT_FETCH_SUCCESS = 'TIMEOUT_HEIGHT_FETCH_SUCCESS';
export const TIMEOUT_HEIGHT_FETCH_ERROR = 'TIMEOUT_HEIGHT_FETCH_ERROR';

export const IBC_BALANCE_FETCH_IN_PROGRESS = 'IBC_BALANCE_FETCH_IN_PROGRESS';
export const IBC_BALANCE_FETCH_SUCCESS = 'IBC_BALANCE_FETCH_SUCCESS';
export const IBC_BALANCE_FETCH_ERROR = 'IBC_BALANCE_FETCH_ERROR';

export const AMINO_SIGN_IBC_TX_IN_PROGRESS = 'AMINO_SIGN_IBC_TX_IN_PROGRESS';
export const AMINO_SIGN_IBC_TX_SUCCESS = 'AMINO_SIGN_IBC_TX_SUCCESS';
export const AMINO_SIGN_IBC_TX_ERROR = 'AMINO_SIGN_IBC_TX_ERROR';

export const IBC_CHANNEL_FETCH_IN_PROGRESS = 'IBC_CHANNEL_FETCH_IN_PROGRESS';
export const IBC_CHANNEL_FETCH_SUCCESS = 'IBC_CHANNEL_FETCH_SUCCESS';
export const IBC_CHANNEL_FETCH_ERROR = 'IBC_CHANNEL_FETCH_ERROR';

export const TX_SIGN_AND_BROAD_CAST_IN_PROGRESS = 'TX_SIGN_AND_BROAD_CAST_IN_PROGRESS';
export const TX_SIGN_AND_BROAD_CAST_SUCCESS = 'TX_SIGN_AND_BROAD_CAST_SUCCESS';
export const TX_SIGN_AND_BROAD_CAST_ERROR = 'TX_SIGN_AND_BROAD_CAST_ERROR';
