export const IBC_TRANSFER_AMOUNT_SET = 'IBC_TRANSFER_AMOUNT_SET';
export const IBC_TRANSFER_TYPE_SET = 'IBC_TRANSFER_TYPE_SET';
export const IBC_SWAP_TYPE_SET = 'IBC_SWAP_TYPE_SET';
export const IBC_TRANSFER_ADDRESS_SET = 'IBC_TRANSFER_ADDRESS_SET';
export const SELECT_CHAIN_SET = 'SELECT_CHAIN_SET';
export const SELECT_ASSET_SET = 'SELECT_ASSET_SET';
export const FROM_NAMADA_SELECT_ASSET_SET = 'FROM_NAMADA_SELECT_ASSET_SET';
export const IBC_TRANSFER_IN_PROGRESS = 'IBC_TRANSFER_IN_PROGRESS';
export const IBC_TRANSFER_SUCCESS = 'IBC_TRANSFER_SUCCESS';
export const IBC_TRANSFER_ERROR = 'IBC_TRANSFER_ERROR';

export const TIMEOUT_HEIGHT_FETCH_IN_PROGRESS = 'TIMEOUT_HEIGHT_FETCH_IN_PROGRESS';
export const TIMEOUT_HEIGHT_FETCH_SUCCESS = 'TIMEOUT_HEIGHT_FETCH_SUCCESS';
export const TIMEOUT_HEIGHT_FETCH_ERROR = 'TIMEOUT_HEIGHT_FETCH_ERROR';
