export const AMOUNT_SET = 'AMOUNT_SET';
export const SELECT_SOURCE_SET = 'SELECT_SOURCE_SET';
export const SHIELDING_SUB_TABS_SET = 'SHIELDING_SUB_TABS_SET';
export const EXTERNAL_SHIELDING_SUB_TABS_SET = 'EXTERNAL_SHIELDING_SUB_TABS_SET';
