import { config } from '../config';

const variables = {
    en: {
        connect_web3: `Connect to your ${config.NETWORK_NAME} ${config.NETWORK_TYPE} account`,
        web3_note: 'web3 power user? Your on-chain data will give you exclusive access',
        select_account: 'Select Account',
        keplr: 'Keplr',
        namada: 'Namada',
        welcome: `Welcome to the ${config.NETWORK_NAME} community`,
        participate: 'Know your validators & interact with the community via governance proposals!',
        total_tokens: 'Total Tokens',
        available_tokens: 'Available Tokens',
        staked_tokens: 'Staked Tokens',
        un_staked_tokens: 'Unstaked Tokens',
        apr: 'APR %',
        staking_apr: 'Staking APR',
        eligible_groups: 'Eligible Groups',
        connect_telegram: 'Connect your Telegram account',
        telegram_communities: 'Participate in exclusive Telegram communities, only for on-chain pros!',
        connect_to_telegram: 'Connect to your Telegram Account',
        connect: 'Connect',
        enter_telegram_username: 'Enter your Telegram username',
        will_receive_otp: 'You will receive an OTP which you have to enter using',
        confirm_username: 'Please confirm your username',
        otp_note1: 'To verify and continue, send a message to ',
        otp_note2: ' in the below format ',
        verify: 'Verify',
        copy: 'Copy',
        copy_otp: 'Copy OTP',
        disconnect: 'Disconnect',
        your_otp: 'Your OTP',
        dashboard: 'Dashboard',
        stake: 'Stake',
        vote: 'Vote',
        proposals: 'Proposals',
        stake_tokens: 'Stake Tokens',
        delegate: 'Delegate',
        un_delegate: 'Undelegate',
        re_delegate: 'Redelegate',
        all_validators: 'All Validators',
        staked_validators: 'Staked Validators',
        inactive_validators: 'Inactive Validators',
        active_validators: 'Active Validators',
        tokens: 'Tokens',
        done: 'Done',
        validator_details: 'Validator Details',
        all: 'All',
        active: 'Passed',
        pending: 'Pending',
        closed: 'Rejected',
        rewards: 'Rewards',
        claim: 'Claim',
        send: 'Send',
        compound: 'Compound',
        vesting_tokens: 'Vesting tokens',
        select_validator: 'Select the validator',
        view_all: 'View All',
        top_active_proposals: 'Top Active Proposals',
        no_data_found: 'No data found',
        success: 'Success',
        transaction_failed: 'Transaction Failed',
        transaction_processing: 'Transaction is in process. use high gas for quick transaction',
        claimed_success: 'CLAIMED TOKENS Successfully',
        vote_success: 'Vote Submitted Successfully',
        transaction_hash: 'Transaction Hash',
        delegator_address: 'Delegator Address',
        validator_address: 'Validator Address',
        approval_pending: 'Approval Pending...',
        connect_account: 'Account not connected. Please connect to wallet',
        connecting: 'connecting',
        cosmostation: 'Cosmostation',
        multi_delegate: 'Multi Delegate',
        number_of_validators: 'Number of Validators',
        tokens_to_each: 'Tokens to each',
        masp: 'MASP',
        ibc_transfer: 'IBC Transfer',
        shielded_available_tokens: 'Shielded Available Tokens',
        select_asset: 'Select Asset',
        internal_shielding: 'Internal Shielding',
        transparent_to_shielding: 'Transparent to Shielding',
        shielded_to_transparent: 'Shielded to Transparent',
        external_ibc_shielding: 'External IBC Shielding',
        ibc_shielding: 'IBC Shielding',
        ibc_unshielding: 'IBC Unshielding',
        external_ibc_transparent: 'External IBC Transparent',
        ibc_chain_to_namada_transparent_transfer: 'IBC Chain to Namada',
        namada_to_ibc_chain_transparent_transfer: 'Namada to IBC Chain',
        internal_transfer: 'Internal Transfer',
        shielding: 'Shielding',
        transfers: 'Transfers',
        external_shielding: 'External Shielding',
        external_transfer: 'External Transfer',
        assets: 'Assets',
        transparent: 'Transparent',
        shielded: 'Shielded',
        claim_and_delegate: 'Claim and Delegate',
        select_a_validator: 'Select Validator',
        claim_rewards: 'Claim Rewards',
        nam_staking_governance: 'Namada Staking & Governance',
        developed_by: 'Developed by',
        unbounding_period: 'Unbonding Period: 14 Days',
        unbounding: 'Unbonding',
        loading: 'Loading...',
        connect_wallet: 'Connect Wallet',
        available: 'Available',
        namada_shielded: 'Namada Shielded',
        namada_transparent: 'Namada Transparent',
        nam_shielded: 'NAM Shielded',
        nam: 'NAM',
        fee: 'Fee',
        ibc_to_namada: 'IBC Transfer to Namada',
        withdraw_namada_ibc: 'Withdraw assets from Namada via IBC',
        unshield_text: 'To withdraw shielded assets please unshield them to your transparent account',
        enables_in_phase_5: 'Enables in Phase 5',
        supported_wallets: 'Supported Wallets',
        transparent_address: 'Transparent Address',
        shielded_address: 'Shielded Address',
        proposal: 'Proposal',
        status: 'Status',
        proposer: 'Proposer',
        submitted_on: 'Submitted on',
        voting_period: 'Voting Period',
        voting_status: 'Voting Status',
        yes: 'YES',
        no: 'NO',
        abstain: 'Abstain',
        type: 'Type',
        cancel: 'Cancel',
        choose_vote: 'Please choose your vote',
        vote_taken: 'your vote is taken: ',
        details: 'Details',
        submitted: 'Submitted',
        proposal_status: 'Proposal Status: ',
        max: 'Max',
        nam_trans_to_nam_shield: 'Namada Transparent to Namada Shielded',
        nam_shield_to_nam_trans: 'Namada Shielded to Namada Transparent',
        from_validator: 'From Validator',
        to_validator: 'To Validator',
        select_multi_validators: 'Select Multi Validators',
        choose_validator: 'Choose the Validator',
        enter_tokens_to: 'Enter Tokens to',
        nothing_selected: 'Nothing Selected',
        out_of: 'out of',
        selected: 'Selected',
        select_all: 'Select All',
        tokens_shielded: 'Tokens Shielded Successfully',
        tokens_trans_success: 'Tokens Transferred Successfully',
        from: 'From',
        to: 'To',
        deposit: 'Deposit',
        withdraw: 'Withdraw',
        transfer_asset: 'Transfer Asset',
        no_data: 'No Data',
        asset: 'Asset',
        memo: 'Memo',
        shield: 'Shield',
        transfer: 'Transfer',
        unshield: 'Unshield',
        sync_again: 'Sync Again',
        withdraw_asset: 'Withdraw Asset',
        deposit_asset: 'Deposit Asset',
        no_tokens_found: 'No Tokens Found',
        coming_soon: 'Coming Soon...',
        shielded_sync_success: 'Shielded synced successfully',
        hang_tight_text: 'Hang tight, this might take a moment',
        shielded_sync_progress: 'Shielded Sync in Progress',
        enter_recipient_address: 'Enter Recipient Address',
        max_available_tokens: 'Max Available Tokens: ',
        stake_with_validator: 'Stake with a Validator now!',
        shielded_balance_uptodate: 'Your shielded balance is now up to date.',
        insufficient_balance: 'Insufficient Balance',
    },
};

export default variables;
