export const config = {
    RPC_URL: 'https://rpc.dydx.nodestake.top:443',
    REST_URL: 'https://rest-dydx.ecostake.com:443',
    EXPLORER_URL: 'https://www.mintscan.io/dydx',
    STAKING_URL: 'https://dydx.omniflix.co/stake',
    WALLET_URL: 'https://dydx.omniflix.co',
    COIN_IMAGE_URL: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx.png',
    NETWORK_NAME: 'dydx',
    NETWORK_TYPE: 'mainnet',
    CHAIN_ID: 'dydx-mainnet-1',
    CHAIN_NAME: 'dydx',
    COIN_DENOM: 'adydx',
    COIN_MINIMAL_DENOM: 'adydx',
    COIN_DECIMALS: 6,
    PREFIX: 'dydx',
    COIN_TYPE: 118,
    COSMOSTAION: 'dydx',
    COINGECKO_ID: 'dydx-chain',
    GAS_PRICE_STEP_LOW: 0.025,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.3,
    FEATURES: ['cosmos_sdk'],
};
